#!/usr/bin/env bash

BACKUP=${1:-mapped/ydb_backup}

export ydb_log=/tmp/yottadb/r1.30_armv7l
export gtm_log=/tmp/yottadb/r1.30_armv7l
export gtm_repl_instance=/root/.yottadb/r1.30_armv7l/g/yottadb.repl
export ydb_repl_instance=/root/.yottadb/r1.30_armv7l/g/yottadb.repl
export ydb_gbldir=/root/.yottadb/r1.30_armv7l/g/yottadb.gld
export ydb_dir=/root/.yottadb
export gtmver='V6.3-008_armv7l'
export ydb_rel=r1.30_armv7l
export gtmgbldir=/root/.yottadb/r1.30_armv7l/g/yottadb.gld
export ydb_routines="/root/.yottadb/r1.30_armv7l/o*(/root/.yottadb/r1.30_armv7l/r /root/.yottadb/r) /usr/local/lib/yottadb/r130/libyottadbutil.so"
export gtmroutines="/root/.yottadb/r1.30_armv7l/o*(/root/.yottadb/r1.30_armv7l/r /root/.yottadb/r) /usr/local/lib/yottadb/r130/libyottadbutil.so"
export gtmdir=/root/.fis-gtm
export ydb_tmp=/tmp/yottadb/r1.30_armv7l
export gtm_tmp=/tmp/yottadb/r1.30_armv7l
export gtm_dist=/usr/local/lib/yottadb/r130
export ydb_dist=/usr/local/lib/yottadb/r130

$ydb_dist/mupip backup "*" -online $BACKUP
