#!/usr/bin/env bash

export ydb_log=/tmp/yottadb/r1.30_armv7l
export gtm_log=/tmp/yottadb/r1.30_armv7l
export gtm_repl_instance=/root/.yottadb/r1.30_armv7l/g/yottadb.repl
export ydb_repl_instance=/root/.yottadb/r1.30_armv7l/g/yottadb.repl
export ydb_gbldir=/root/.yottadb/r1.30_armv7l/g/yottadb.gld
export ydb_dir=/root/.yottadb
export gtmver='V6.3-008_armv7l'
export ydb_rel=r1.30_armv7l
export gtmgbldir=/root/.yottadb/r1.30_armv7l/g/yottadb.gld
export ydb_routines="/opt/qewd/node_modules/nodem/src /root/.yottadb/r1.30_armv7l/o*(/root/.yottadb/r1.30_armv7l/r /root/.yottadb/r) /usr/local/lib/yottadb/r130/libyottadbutil.so"
export gtmroutines="/opt/qewd/node_modules/nodem/src /root/.yottadb/r1.30_armv7l/o*(/root/.yottadb/r1.30_armv7l/r /root/.yottadb/r) /usr/local/lib/yottadb/r130/libyottadbutil.so"
#export GTMCI=/opt/qewd/node_modules/nodem/resources/nodem.ci
#export ydb_ci=/opt/qewd/node_modules/nodem/resources/nodem.ci
export gtmdir=/root/.fis-gtm
export ydb_tmp=/tmp/yottadb/r1.30_armv7l
export gtm_tmp=/tmp/yottadb/r1.30_armv7l
export gtm_dist=/usr/local/lib/yottadb/r130
export ydb_dist=/usr/local/lib/yottadb/r130

# stop and restart journalling, removing the old journal file

$ydb_dist/mupip set -journal=disable -region DEFAULT 
rm /root/.yottadb/r1.30_armv7l/g/yottadb.mjl
$ydb_dist/mupip set -journal=enable,before,file=/root/.yottadb/r1.30_armv7l/g/yottadb.mjl -region DEFAULT
