#!/usr/bin/env bash

export ydb_log=/tmp/yottadb/r1.30_x86_64
export gtm_log=/tmp/yottadb/r1.30_x86_64
export gtm_repl_instance=/root/.yottadb/r1.30_x86_64/g/yottadb.repl
export ydb_repl_instance=/root/.yottadb/r1.30_x86_64/g/yottadb.repl
export ydb_gbldir=/root/.yottadb/r1.30_x86_64/g/yottadb.gld
export ydb_dir=/root/.yottadb
export gtmver='V6.3-008_x86_64'
export ydb_rel=r1.30_x86_64
export gtmgbldir=/root/.yottadb/r1.30_x86_64/g/yottadb.gld
export ydb_routines="/root/.yottadb/r1.30_x86_64/o*(/root/.yottadb/r1.30_x86_64/r /root/.yottadb/r) /usr/local/lib/yottadb/r130/libyottadbutil.so"
export gtmroutines="/root/.yottadb/r1.30_x86_64/o*(/root/.yottadb/r1.30_x86_64/r /root/.yottadb/r) /usr/local/lib/yottadb/r130/libyottadbutil.so"
export gtmdir=/root/.fis-gtm
export ydb_tmp=/tmp/yottadb/r1.30_x86_64
export gtm_tmp=/tmp/yottadb/r1.30_x86_64
export gtm_dist=/usr/local/lib/yottadb/r130
export ydb_dist=/usr/local/lib/yottadb/r130

# stop and restart journalling, removing the old journal file

$ydb_dist/mupip set -journal=disable -region DEFAULT 
rm /root/.yottadb/r1.30_x86_64/g/yottadb.mjl
$ydb_dist/mupip set -journal=enable,before,file=/root/.yottadb/r1.30_x86_64/g/yottadb.mjl -region DEFAULT
